# COINGECKO API KEY SETTING
coingecko:
  api_key: ${COINGECKO_ACCESS_KEY}
  api_url: https://api.coingecko.com/api/v3


# MINIO SETTINGS
storage_minio:
  minio_endpoint: 172.18.0.10:9000
  minio_access_key: crypto_admin
  minio_secret_key: crypto_password
  minio_root_user: crypto_admin
  minio_root_password: crypto_password